Webtruyen/Webtruyen/Controllers/HomeClientController.cs
using Models;
using Models.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Webtruyen.Controllers
{
    public class HomeClientController : Controller
    {
        // GET: HomeClient
        public ActionResult Index()
        {
            //var listT = new TruyenModel();
            //var model = listT.ListAll();
            var model = new TruyenDao().Listtruyenfull();
            ViewBag.truyenmoi = new TruyenDao().Listtruyenmoi();
            ViewBag.Chuongmoinhat = new TruyenDao().Chuongmoinhat();
            return View(model);
        }
        //menu
        //[ChildActionOnly]
        public ActionResult _TheloaiPartial()
        {
            var model = new TheLoaiDao().ListAll();
            return PartialView(model);
        }
        public ActionResult TruyenhotPartial()
        {
            var model = new TruyenDao().TruyenhotPartial();
            return PartialView(model);
        }
        public ActionResult LoaitruyenPartial()
        {
            var model = new LoaitruyenDao().ListAll();
            return PartialView(model);
        }
        public ActionResult OtimkiemPartial()
        {
            return View();
        }



    }
}

Webtruyen/Webtruyen/Controllers/TimkiemController.cs
using Models;
using Models.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Microsoft.Owin;

namespace Webtruyen.Controllers
{
    public class TimkiemController : Controller
    {
        // GET: Timkiem
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Timkiemtheloai(int id, int page = 1, int pageSize = 10)
        {
            var tk = new TruyenDao().TruyentheoTLPagedList(id, page, pageSize);
            ViewBag.maTL = new TheLoaiDao().ViewDetail(id);
            ViewBag.sl=new TruyenDao().TruyentheoTL(id).Count();
                return View(tk);
        }
        public ActionResult Timkiemtruyenabc(int page = 1, int pageSize = 10)
        {
            var tk = new TruyenDao().ListTabcpagelist(page, pageSize);
            // ViewBag.sl =tk.Count();
            return View(tk);
        }
        public ActionResult Timkiemtruyenmoi(int page =1, int pageSize=10)
        {
            var tk = new TruyenDao().ListTMpagelist(page,pageSize);
           // ViewBag.sl =tk.Count();
            return View(tk);
        }
        public ActionResult Timkiemtruyenhot(int page = 1, int pageSize = 10)
        {
            var tk = new TruyenDao().ListTHpagelist(page, pageSize);
            return View(tk);
        }
        public ActionResult Timkiemtruyentacgia(string tg,int page = 1, int pageSize = 10)
        {
            var tk = new TruyenDao().ListTTGpagelist(tg,page, pageSize);
            ViewBag.tg = tg;
            return View(tk);
        }
        public ActionResult Timkiemloaitruyen(int id, int page = 1, int pageSize = 10)
        {
            var tk = new TruyenDao().ListTtheoloaipagelist(id, page, pageSize);
            ViewBag.loai = new LoaitruyenDao().ViewDetail(id);
            //ViewBag.sl = new TruyenDao().TruyentheoTL(id).Count();
            return View(tk);
        }
        //====================================
        public ActionResult Timkiemtruyenaudio(int page = 1, int pageSize = 10)
        {
            var tk = new TruyenaudioDao().ListAllpagelist(page, pageSize);
            return View(tk);
        }
        public ActionResult Timkiemtruyentranh(int page = 1, int pageSize = 10)
        {
            var tk = new TruyentranhDao().ListAllpagelist(page, pageSize);
            return View(tk);
        }
        public ActionResult Timkiemtukhoa(string q, int page = 1, int pageSize = 10)
        {
            //string tk = f["q"].ToString();

            var t = new TruyenDao().ListOTKpagelist(q, page, pageSize);
            ViewBag.tk = q;

            return View(t);
        }


    }
}

Webtruyen/Webtruyen/Views/Timkiem/Timkiemloaitruyen.cshtml
@model PagedList.IPagedList<Models.Framework.TRUYEN>
@using PagedList.Mvc;
<link href="~/Content/Nguoidungtimkiem.css" rel="stylesheet" />
@{
    ViewBag.Title = "Timkiemloaitruyen";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
    var loai = (Models.Framework.LOAITRUYEN)ViewBag.loai;
   
}

<style>
    img {
        margin-top: -20%;
        /*margin-bottom: -100px;*/
    }

    /*div#anhtk {
        width: 200px;
        height: 100px;
        border: 1px dotted black;
        overflow: hidden;
    }*/
</style>

<!--=============================================-->
<div class="container">
    <div class="products-page">

        <div class="new-product">
            @*<div class="new-product-top">
                    <ul class="product-top-list">

                    </ul>

                    <div class="clearfix"></div>
                </div>*@

            @*<div id="cbp-vm" class="cbp-vm-switcher cbp-vm-view-grid">
                    <ul>

                    </ul>
                </div>*@
            <!---------------------------->
            <div>
                <h3 class="first">Loại truyện: @loai.Tenloai</h3>
                <div class="">
                    <table class="table table-hover">
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td id="cotanhtk" width="210">
                                        <div id="anhtk" class="reponsive">
                                            <a href="/Doctruyen/Chitiettruyen/@item.Matruyen"><img id="anhbiatk" style="cursor:auto" src="@item.Anhbia" width="200" /></a>
                                        </div>
                                    </td>
                                    <td>
                                        <p id="tentruyenCM">
                                            <a class="" href="/Doctruyen/Chitiettruyen/@item.Matruyen"><span id="p" style="font-family:Calibri;font-size:120%; color:sienna;"><strong>@item.Tentruyen</strong></span></a>
                                        </p>
                                        <p>
                                            ✎&nbsp;&nbsp;@item.Tacgia<br />
                                            ღ&nbsp;&nbsp;@item.Sochuong &nbsp;chương<br />
                                            ❦&nbsp;&nbsp;@item.Tacgia
                                        </p>
                                    </td>
                                    @* <td>Otto</td>*@

                                </tr>

                            }


                        </tbody>
                    </table>
                    @Html.PagedListPager(Model, page => Url.Action("Timkiemloaitruyen", new { id = @loai.Maloai, page = page }))

                    <div class="clearfix"></div>
                </div>
            </div>




            <!------------------------>

            <script src="/Assets/Client/js/cbpViewModeSwitch.js" type="text/javascript"></script>
            <script src="/Assets/Client/js/classie.js" type="text/javascript"></script>
        </div>
        <div class="products">

            <div class="product-listy">
                <h2>Thể loại</h2>
                <ul class="product-list">
                    <!--<li><a href="">New Products</a></li>-->
                    @Html.Action("_TheloaiPartial", "HomeClient")

                </ul>
            </div>

            <div class="tags">
                <h4 class="tag_head">Truyện hot</h4>
                <ul class="tags_links"></ul>
                <div class="bs-example">
                    <table class="table">
                        <tbody>
                            @Html.Action("TruyenhotPartial", "HomeClient")
                            @*<tr>

                                    <td class="type-info">Semibold 36px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 30px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 24px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 18px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 14px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 12px</td>
                                </tr>*@

                        </tbody>
                    </table>
                </div>

            </div>

            <div class="latest-bis">
                <br /><br /><br />
                <div class="offer">
                    <p>TOP</p>
                    <small>10 truyện</small>
                </div>
            </div>



        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- content-section-ends -->
<!--========================================-->

Webtruyen/Webtruyen/Views/Timkiem/Timkiemtheloai.cshtml
@model PagedList.IPagedList<Models.Framework.TRUYEN>
@using PagedList.Mvc;
<link href="~/Content/Nguoidungtimkiem.css" rel="stylesheet" />
@{
    ViewBag.Title = "Timkiemtheloai";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
    var theloai = (Models.Framework.THELOAI)ViewBag.maTL;
    int sl = (int)ViewBag.sl;
}

<style>
    img {
        margin-top: -20%;
        /*margin-bottom: -100px;*/
    }

    /*div#anhtk {
        width: 200px;
        height: 100px;
        border: 1px dotted black;
        overflow: hidden;
    }*/
</style>

<!--=============================================-->
<div class="container">
    <div class="products-page">

        <div class="new-product">
            @*<div class="new-product-top">
                    <ul class="product-top-list">

                    </ul>

                    <div class="clearfix"></div>
                </div>*@

            @*<div id="cbp-vm" class="cbp-vm-switcher cbp-vm-view-grid">
                    <ul>

                    </ul>
                </div>*@
            <!---------------------------->
            <div>
                <h3 class="first">Thể loại: @theloai.Tentheloai (tìm thấy @sl truyện)</h3>
                <div class="">
                    <table class="table table-hover">
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td id="cotanhtk" width="210">
                                        <div id="anhtk" class="reponsive">
                                            <a href="/Doctruyen/Chitiettruyen/@item.Matruyen"><img id="anhbiatk" style="cursor:auto" src="@item.Anhbia" width="200" /></a>
                                        </div>
                                    </td>
                                    <td>
                                        <p id="tentruyenCM">
                                            <a class="" href="/Doctruyen/Chitiettruyen/@item.Matruyen"><span id="p" style="font-family:Calibri;font-size:120%; color:sienna;"><strong>@item.Tentruyen</strong></span></a>
                                        </p>
                                        <p>
                                            ✎&nbsp;&nbsp;@item.Tacgia<br />
                                            ღ&nbsp;&nbsp;@item.Sochuong &nbsp;chương<br />
                                            ❦&nbsp;&nbsp;@item.Tacgia
                                        </p>
                                    </td>
                                    @* <td>Otto</td>*@

                                </tr>

                            }


                        </tbody>
                    </table>
                    @Html.PagedListPager(Model, page => Url.Action("Timkiemtheloai", new { id=@theloai.Matheloai, page=page }))

                    <div class="clearfix"></div>
                </div>
            </div>




            <!------------------------>

            <script src="/Assets/Client/js/cbpViewModeSwitch.js" type="text/javascript"></script>
            <script src="/Assets/Client/js/classie.js" type="text/javascript"></script>
        </div>
        <div class="products">

            <div class="product-listy">
                <h2>Thể loại</h2>
                <ul class="product-list">
                    <!--<li><a href="">New Products</a></li>-->
                    @Html.Action("_TheloaiPartial", "HomeClient")

                </ul>
            </div>

            <div class="tags">
                <h4 class="tag_head">Truyện hot</h4>
                <ul class="tags_links"></ul>
                <div class="bs-example">
                    <table class="table">
                        <tbody>
                            @Html.Action("TruyenhotPartial", "HomeClient")
                            @*<tr>

                            <td class="type-info">Semibold 36px</td>
                        </tr>
                        <tr>

                            <td class="type-info">Semibold 30px</td>
                        </tr>
                        <tr>

                            <td class="type-info">Semibold 24px</td>
                        </tr>
                        <tr>

                            <td class="type-info">Semibold 18px</td>
                        </tr>
                        <tr>

                            <td class="type-info">Semibold 14px</td>
                        </tr>
                        <tr>

                            <td class="type-info">Semibold 12px</td>
                        </tr>*@

                        </tbody>
                    </table>
                </div>

            </div>

            <div class="latest-bis">
                <br /><br /><br />
                <div class="offer">
                    <p>TOP</p>
                    <small>10 truyện</small>
                </div>
            </div>



        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- content-section-ends -->
<!--========================================-->





   

Webtruyen/Webtruyen/Views/Timkiem/Timkiemtruyenabc.cshtml
@model PagedList.IPagedList<Models.Framework.TRUYEN>
@using PagedList.Mvc;
<link href="~/Content/Nguoidungtimkiem.css" rel="stylesheet" />
@{
    ViewBag.Title = "Timkiemtruyenabc";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
    //int sl = (int)ViewBag.sl;
}

<style>
    img {
        margin-top: -20%;
        /*margin-bottom: -100px;*/
    }

    /*div#anhtk {
        width: 200px;
        height: 100px;
        border: 1px dotted black;
        overflow: hidden;
    }*/
</style>

<!--=============================================-->
<div class="container">
    <div class="products-page">

        <div class="new-product">

            <!---------------------------->
            <div>
                <h3 class="first">Truyện theo abc</h3>
                <div class="">
                    <table class="table table-hover">
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td id="cotanhtk" width="210">
                                        <div id="anhtk" class="reponsive">
                                            <a href="/Doctruyen/Chitiettruyen/@item.Matruyen"><img id="anhbiatk" style="cursor:auto" src="@item.Anhbia" width="200" /></a>
                                        </div>
                                    </td>
                                    <td>
                                        <p id="tentruyenCM">
                                            <a class="" href="/Doctruyen/Chitiettruyen/@item.Matruyen"><span id="p" style="font-family:Calibri;font-size:120%; color:sienna;"><strong>@item.Tentruyen</strong></span></a>
                                        </p>
                                        <p>
                                            ✎&nbsp;&nbsp;@item.Tacgia<br />
                                            ღ&nbsp;&nbsp;@item.Sochuong &nbsp;chương<br />
                                            ❦&nbsp;&nbsp;@item.Ngaycapnhat
                                        </p>
                                    </td>
                                    @* <td>Otto</td>*@

                                </tr>

                            }


                        </tbody>
                    </table>
                    @Html.PagedListPager(Model, page => Url.Action("Timkiemtruyenabc", new { page }))

                    <div class="clearfix"></div>
                </div>
            </div>




            <!------------------------>

            <script src="/Assets/Client/js/cbpViewModeSwitch.js" type="text/javascript"></script>
            <script src="/Assets/Client/js/classie.js" type="text/javascript"></script>
        </div>
        <div class="products">

            <div class="product-listy">
                <h2>Thể loại</h2>
                <ul class="product-list">
                    <!--<li><a href="">New Products</a></li>-->
                    @Html.Action("_TheloaiPartial", "HomeClient")

                </ul>
            </div>

            <div class="tags">
                <h4 class="tag_head">Truyện hot</h4>
                <ul class="tags_links"></ul>
                <div class="bs-example">
                    <table class="table">
                        <tbody>
                            @Html.Action("TruyenhotPartial", "HomeClient")
                            @*<tr>

                                    <td class="type-info">Semibold 36px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 30px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 24px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 18px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 14px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 12px</td>
                                </tr>*@

                        </tbody>
                    </table>
                </div>

            </div>

            <div class="latest-bis">
                <br /><br /><br />
                <div class="offer">
                    <p>TOP</p>
                    <small>10 truyện</small>
                </div>
            </div>



        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- content-section-ends -->
<!--========================================-->
@*<div>
        @{ int i = 0;}
        @foreach (var item in Model)
                {
                    i++;
            <div id="tktruyen" class="col-md-12 col-sm-12">
                <div class="row">
                   <div id="anhtk" class="crop">
                        <a href="/Doctruyen/Chitiettruyen/@item.Matruyen"><img style="cursor:auto" src="@item.Anhbia" height="350" class="crop" /></a>
                   </div>
                    <div class="tenttk">
                        <a href="/Doctruyen/Chitiettruyen/@item.Matruyen"><span style="font-family:Arial">@item.Tentruyen</span></a>
                        <p>Full-@item.Sochuong Chương</p>
                    </div>
                </div>
            </div>
            if (i % 2 == 0)
            {
                <div style="clear:both"></div>
            }
        }
    </div>*@

Webtruyen/Webtruyen/Views/Timkiem/Timkiemtruyenaudio.cshtml
@model PagedList.IPagedList<Models.Framework.TRUYENAUDIO>
@using PagedList.Mvc;
<link href="~/Content/Nguoidungtimkiem.css" rel="stylesheet" />
@{
    ViewBag.Title = "Timkiemtruyenaudio";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}


<style>
    img {
        margin-top: -20%;
        /*margin-bottom: -100px;*/
    }

    /*div#anhtk {
        width: 200px;
        height: 100px;
        border: 1px dotted black;
        overflow: hidden;
    }*/
</style>

<!--=============================================-->
<div class="container">
    <div class="products-page">

        <div class="new-product">

            <!---------------------------->
            <div>
                <h3 class="first">Truyện audio</h3>
                <div class="">
                    <table class="table table-hover">
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td id="cotanhtk" width="210">
                                        <div id="anhtk" class="reponsive">
                                            <a href="/Doctruyen/Nghetruyenaudio/@item.Matruyen"><img id="anhbiatk" style="cursor:auto" src="@item.Anhbia" width="200" /></a>
                                        </div>
                                    </td>
                                    <td>
                                        <p id="tentruyenCM">
                                            <a class="" href="/Doctruyen/Nghetruyenaudio/@item.Matruyen"><span id="p" style="font-family:Calibri;font-size:120%; color:sienna;"><strong>@item.Tentruyen</strong></span></a>
                                        </p>
                                        <p>
                                            ✎&nbsp;&nbsp;@item.Tacgia<br />
                                            ☼&nbsp;&nbsp;@item.Solandoc lượt nghe<br/>
                                            ❦&nbsp;&nbsp;@item.Ngaycapnhat
                                        </p>
                                    </td>
                                    @* <td>Otto</td>*@

                                </tr>

                            }


                        </tbody>
                    </table>
                    @Html.PagedListPager(Model, page => Url.Action("Timkiemtruyenaudio", new { page }))

                    <div class="clearfix"></div>
                </div>
            </div>




            <!------------------------>

            <script src="/Assets/Client/js/cbpViewModeSwitch.js" type="text/javascript"></script>
            <script src="/Assets/Client/js/classie.js" type="text/javascript"></script>
        </div>
        <div class="products">

            <div class="product-listy">
                <h2>Thể loại</h2>
                <ul class="product-list">
                    <!--<li><a href="">New Products</a></li>-->
                    @Html.Action("_TheloaiPartial", "HomeClient")

                </ul>
            </div>

            <div class="tags">
                <h4 class="tag_head">Truyện hot</h4>
                <ul class="tags_links"></ul>
                <div class="bs-example">
                    <table class="table">
                        <tbody>
                            @Html.Action("TruyenhotPartial", "HomeClient")
                            @*<tr>

                                    <td class="type-info">Semibold 36px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 30px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 24px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 18px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 14px</td>
                                </tr>
                                <tr>

                                    <td class="type-info">Semibold 12px</td>
                                </tr>*@

                        </tbody>
                    </table>
                </div>

            </div>

            <div class="latest-bis">
                <br /><br /><br />
                <div class="offer">
                    <p>TOP</p>
                    <small>10 truyện</small>
                </div>
            </div>



        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- content-section-ends -->
<!--========================================-->

Webtruyen/Webtruyen/Views/Timkiem/Timkiemtruyenhot.cshtml
@model PagedList.IPagedList<Models.Framework.TRUYEN>
@using PagedList.Mvc;
<link href="~/Content/Nguoidungtimkiem.css" rel="stylesheet" />
@{
    ViewBag.Title = "Timkiemtruyenhot";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
   
}

<style>
    img {
        margin-top: -20%;
        /*margin-bottom: -100px;*/
    }

    /*div#anhtk {
        width: 200px;
        height: 100px;
        border: 1px dotted black;
        overflow: hidden;
    }*/
</style>

<!--=============================================-->
<div class="container">
    <div class="products-page">

        <div class="new-product">

            <!---------------------------->
            <div>
                <h3 class="first">Truyện xem nhiều</h3>
                <div class="">
                    <table class="table table-hover">
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td id="cotanhtk" width="210">
                                        <div id="anhtk" class="reponsive">
                                            <a href="/Doctruyen/Chitiettruyen/@item.Matruyen"><img id="anhbiatk" style="cursor:auto" src="@item.Anhbia" width="200" /></a>
                                        </div>
                                    </td>
                                    <td>
                                        <p id="tentruyenCM">
                                            <a class="" href="/Doctruyen/Chitiettruyen/@item.Matruyen"><span id="p" style="font-family:Calibri;font-size:120%; color:sienna;"><strong>@item.Tentruyen</strong></span></a>
                                        </p>
                                        <p>
                                            ✎&nbsp;&nbsp;@item.Tacgia<br />
                                            ❄&nbsp;&nbsp;@item.Sochuong &nbsp;chương<br />
                                            ☼&nbsp;&nbsp;Lượt xem: @item.Solandoc
                                        </p>
                                    </td>
                                    @* <td>Otto</td>*@

                                </tr>

                            }


                        </tbody>
                    </table>
                    @Html.PagedListPager(Model, page => Url.Action("Timkiemtruyenhot", new { page }))

                    <div class="clearfix"></div>
                </div>
            </div>




            <!------------------------>

            <script src="/Assets/Client/js/cbpViewModeSwitch.js" type="text/javascript"></script>
            <script src="/Assets/Client/js/classie.js" type="text/javascript"></script>
        </div>
        <div class="products">

            <div class="product-listy">
                <h2>Thể loại</h2>
                <ul class="product-list">
                    <!--<li><a href="">New Products</a></li>-->
                    @Html.Action("_TheloaiPartial", "HomeClient")

                </ul>
            </div>

            <div class="tags">
                <h4 class="tag_head">Truyện hot</h4>
                <ul class="tags_links"></ul>
                <div class="bs-example">
                    <table class="table">
                        <tbody>
                            @Html.Action("TruyenhotPartial", "HomeClient")
                            @*<tr>

                            <td class="type-info">Semibold 36px</td>
                        </tr>
                        <tr>

                            <td class="type-info">Semibold 30px</td>
                        </tr>
                        <tr>

                            <td class="type-info">Semibold 24px</td>
                        </tr>
                        <tr>

                            <td class="type-info">Semibold 18px</td>
                        </tr>
                        <tr>

                            <td class="type-info">Semibold 14px</td>
                        </tr>
                        <tr>

                            <td class="type-info">Semibold 12px</td>
                        </tr>*@

                        </tbody>
                    </table>
                </div>

            </div>

            <div class="latest-bis">
                <br /><br /><br />
                <div class="offer">
                    <p>TOP</p>
                    <small>10 truyện</small>
                </div>
            </div>



        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- content-section-ends -->
<!--========================================-->
@*<div>
        @{ int i = 0;}
        @foreach (var item in Model)
                {
                    i++;
            <div id="tktruyen" class="col-md-12 col-sm-12">
                <div class="row">
                   <div id="anhtk" class="crop">
                        <a href="/Doctruyen/Chitiettruyen/@item.Matruyen"><img style="cursor:auto" src="@item.Anhbia" height="350" class="crop" /></a>
                   </div>
                    <div class="tenttk">
                        <a href="/Doctruyen/Chitiettruyen/@item.Matruyen"><span style="font-family:Arial">@item.Tentruyen</span></a>
                        <p>Full-@item.Sochuong Chương</p>
                    </div>
                </div>
            </div>
            if (i % 2 == 0)
            {
                <div style="clear:both"></div>
            }
        }
    </div>*@