Webtruyen/Webtruyen/Controllers/DoctruyenController.cs
using Models.Dao;
using Models.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Webtruyen.Controllers
{
    public class DoctruyenController : Controller
    {
        // GET: Doctruyen
        public ActionResult Chitiettruyen(int id, int page = 1, int pageSize = 15)
        {    

             var truyen = new TruyenDao().ViewDetail(id);
            var flat = new TruyenDao().UpdateSLD(truyen);
            ViewBag.truyen = truyen;
            ViewBag.theloai = new TruyentheloaiDao().ListTLT(id);
            //var t = new TruyenDao().ViewDetail(id);
            ViewBag.Page = page;
            ViewBag.Cungtacgia = new TruyenDao().ListTCTG(truyen.Tacgia);

            var listC = new ChuongDao().ListAllpagelist(id, page, pageSize);
            return View(listC);
        }

        public ActionResult ChuongtruyenPartial(int id)
        {
            List<CHUONG>  listC= new ChuongDao().ListByChuongId(id);
            return PartialView(listC);
        }


        public ActionResult DocChuong(int id)
        {
            
            CHUONG chuong = new ChuongDao().ViewDetail(id);

            int maT = chuong.Matruyen.GetValueOrDefault();

            ViewBag.chuongT = chuong;
            ViewBag.truyen = new TruyenDao().ViewDetail(maT);
            ViewBag.listC = new ChuongDao().ListByChuongId(maT);

            var tr = new TruyenDao().ViewDetail(maT);
            ViewBag.chuongtruoc = new TruyenDao().Laymachuongtruoc(chuong.Matruyen, chuong.Thutuchuong);
            ViewBag.chuongtiep = new TruyenDao().Laymachuongtiep(chuong.Matruyen, chuong.Thutuchuong);
            ViewBag.Tentruyen = tr.Tentruyen;
            

            return View(chuong);
        }
        public ActionResult TentruyenPartial(int id)
        {
            var truyen = new TruyenDao().ViewDetail(id);
            return View(truyen);
        }
        public ActionResult CungtacgiaPartial(string tg)
        {
            var tk = new TruyenDao().ListTCTG(tg);
            return View(tk);
        }

        //====================================================

        public ActionResult Nghetruyenaudio(int id)
        {
            var truyen = new TruyenaudioDao().ViewDetail(id);
            ViewBag.truyenaudio = truyen;
            ViewBag.truyenlq = new TruyenaudioDao().List10truyenaudio();
            var flat = new TruyenaudioDao().UpdateSLD(truyen);
            return View();
        }
        public ActionResult Xemtruyentranh(int id)
        {
            var truyen = new TruyentranhDao().ViewDetail(id);
            ViewBag.truyentranh = truyen;
            ViewBag.truyenlq = new TruyentranhDao().List10truyenaudio();
            var flat = new TruyentranhDao().UpdateSLD(truyen);
            return View();
        }
    }
}

Webtruyen/Webtruyen/Controllers/TimkiemController.cs
using Models;
using Models.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Microsoft.Owin;

namespace Webtruyen.Controllers
{
    public class TimkiemController : Controller
    {
        // GET: Timkiem
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Timkiemtheloai(int id, int page = 1, int pageSize = 10)
        {
            var tk = new TruyenDao().TruyentheoTLPagedList(id, page, pageSize);
            ViewBag.maTL = new TheLoaiDao().ViewDetail(id);
            ViewBag.sl=new TruyenDao().TruyentheoTL(id).Count();
                return View(tk);
        }
        public ActionResult Timkiemtruyenabc(int page = 1, int pageSize = 10)
        {
            var tk = new TruyenDao().ListTabcpagelist(page, pageSize);
            // ViewBag.sl =tk.Count();
            return View(tk);
        }
        public ActionResult Timkiemtruyenmoi(int page =1, int pageSize=10)
        {
            var tk = new TruyenDao().ListTMpagelist(page,pageSize);
           // ViewBag.sl =tk.Count();
            return View(tk);
        }
        public ActionResult Timkiemtruyenhot(int page = 1, int pageSize = 10)
        {
            var tk = new TruyenDao().ListTHpagelist(page, pageSize);
            return View(tk);
        }
        public ActionResult Timkiemtruyentacgia(string tg,int page = 1, int pageSize = 10)
        {
            var tk = new TruyenDao().ListTTGpagelist(tg,page, pageSize);
            ViewBag.tg = tg;
            return View(tk);
        }
        public ActionResult Timkiemloaitruyen(int id, int page = 1, int pageSize = 10)
        {
            var tk = new TruyenDao().ListTtheoloaipagelist(id, page, pageSize);
            ViewBag.loai = new LoaitruyenDao().ViewDetail(id);
            //ViewBag.sl = new TruyenDao().TruyentheoTL(id).Count();
            return View(tk);
        }
        //====================================
        public ActionResult Timkiemtruyenaudio(int page = 1, int pageSize = 10)
        {
            var tk = new TruyenaudioDao().ListAllpagelist(page, pageSize);
            return View(tk);
        }
        public ActionResult Timkiemtruyentranh(int page = 1, int pageSize = 10)
        {
            var tk = new TruyentranhDao().ListAllpagelist(page, pageSize);
            return View(tk);
        }
        public ActionResult Timkiemtukhoa(string q, int page = 1, int pageSize = 10)
        {
            //string tk = f["q"].ToString();

            var t = new TruyenDao().ListOTKpagelist(q, page, pageSize);
            ViewBag.tk = q;

            return View(t);
        }


    }
}

Webtruyen/Webtruyen/Views/Doctruyen/Chitiettruyen.cshtml
@model PagedList.IPagedList<Models.Framework.CHUONG>
@using PagedList.Mvc;
<link href="/Content/Chitiettruyen.css" rel="stylesheet" />
@{
    ViewBag.Title = "Chitiettruyen";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
    var truyen = (Models.Framework.TRUYEN)ViewBag.truyen;
    var cungtacgia = (IEnumerable<Models.Framework.TRUYEN>)ViewBag.Cungtacgia;
    var theloai = (List<Models.ViewModel.TheloaitruyenViewModel>)ViewBag.theloai;
    int Page = (int)ViewBag.Page;
}



@using (Html.BeginForm())
{
    <br />
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Homeclient")">Trang chủ</a></li>
        <li><a href="@Url.Action("Timkiemtruyenabc","Timkiem")">Truyện chữ</a></li>
        <li class="active">@truyen.Tentruyen</li>

    </ol>
    <div class="form-horizontal">
        @Html.AntiForgeryToken()

        <!--<div id="page-wrapper">-->
        <div class="row">
            <div class="col-lg-12">
                <div class="container">
                    <h1>                       <br />                                                    </h1>
                    <div class="bars"><p id="tieude" class="text-center">   »——(¯` THÔNG TIN TRUYỆN ´¯)——»</p></div>
                    <h6 class="text-center">¸.•♥•.¸¸.•♥•  (>‿◠)✌ •♥•.¸¸.•♥•.¸</h6>
                </div>
            </div>
        </div>
        <!--==========================================================-->
        <div class="row">
            <div class="col-lg-9">
                <div class="container">
                    <div class="heading bars text-center">
                        <!--Tên truyện-->

                        <p id="tentruyentieude">
                            <span style="font-family: Arial; font-size: 200%;color:dodgerblue; font:bold ">

                                @truyen.Tentruyen
                                <br /> <br />
                            </span>
                        </p>
                    </div>
                    
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-12">
                <div class="container col-lg-12">                   
                        <div class="col-lg-3 col-md-12">
                            <div class="row">
                                <div id="anhct" class="img-responsive">
                                    <!--Ảnh-->
                                    <img id="Anhbiact" style="cursor:auto" src="@truyen.Anhbia" width="250" />

                                </div>                                
                                    <div>
                                        <!--Thông tin cơ bản-->
                                        <p>
                                            <br />
                                            <div class="fb-like text-center" expr:data-href='data:post.url' data-layout="button" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
                                            <br />
                                            <span style="font-family:Arial; color:gray ">
                                                <br />
                                                Tác giả:  <a href="@Url.Action("Timkiemtruyentacgia","Timkiem",new { tg = @truyen.Tacgia })"><span style="color:dimgray"><strong>@truyen.Tacgia</strong></span></a>
                                                <br />
                                                Tình trạng:  @truyen.Tinhtrang
                                                <br />
                                                Số chương:  @truyen.Sochuong
                                                <br />
                                                Nguồn:  @truyen.Nguon
                                                <br />
                                                @truyen.Solandoc  lượt xem
                                                <br />Thể loại:
                                                @{ int i = 0;}
                                                @foreach (var item in theloai)
                                                {
                                                    if (i < theloai.Count - 1)
                                                    {
                                                        <a href="@Url.Action("Timkiemtheloai","Timkiem",new { id= @item.Matheloai})">
                                                            <span style="color:dimgray"><strong>  @item.Tentheloai,  </strong></span></a>
                                                    }
                                                    else
                                                    {
                                                        <a href="@Url.Action("Timkiemtheloai","Timkiem",new { id= @item.Matheloai})">
                                                            <span style="color:dimgray"><strong>  @item.Tentheloai  </strong></span></a>

                                                    }
                                                    i++;

                                                }
                                            </span>
                                            <br /><br />
                                        </p>
                                        
                                        

                                    </div>                             
                                
                                        <div>
                                            <!--Partial thể loại-->
                                        </div>                                    
                            </div> 
                        </div>
                    
                        <div>
                                                           
                                <div>
                                    <div>
                                        
                                            <!--văn án-->
                                            <span style="font-family: Arial; font-size: 28px;color:dimgray ">
                                                   Giới thiệu truyện: <br /><br />
                                                </span>
                                        <div class="mota">
                                           
                                                <span style="font-family:Arial; color:gray ">
                                                    @Html.Raw(truyen.Mota)

                                                </span>
                                           
                                        </div>
                                    </div>
                                </div>

                            
                        </div>
                   
                </div>
            </div>
        </div>
        <!--===========================================================-->
        <!--=============================================-->
        <div class="container">
            <div class="products-page">

                <div class="new-product">
                   
                    <!---------------------------->
                    <div>
                        <h3 class="first"><p><span style="font-family: Arial; font-size: 28px;color:dimgray "><br />Danh mục chương</span></p></h3>
                        <div class="mota">
                            <table class="table table-hover">
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr id="row_@item.Machuong" class="odd gradeX">
                                            @*<td class="text-center">@item.Machuong</td>*@
                                            <td class="text-center"><span style="font-family:Arial;color:darkgray ">@item.Thutuchuong</span></td>
                                            <td>
                                                <a href="@Url.Action("Docchuong","Doctruyen",new { id = @item.Machuong })">
                                                    <p><span style="font-family:Arial; color:darkgray ">@item.Tenchuong</span></p>
                                                </a>

                                            </td>
                                            <td class="text-center"><span style="color:darkgray ">@item.Capnhatchuong</span></td>
                                        </tr>

                                    }


                                </tbody>
                            </table>

                            @Html.PagedListPager(Model, page => Url.Action("Chitiettruyen", new { id = @truyen.Matruyen, page }))
                            <div class="clearfix"></div>
                        </div>
                        <h3 class="first"><p><span style="font-family: Arial; font-size: 28px;color:dimgray "><br />Bình luận</span></p></h3>
                        <div class="">
                            <table class="table">
                                <tbody>
                                    <tr class="text-center odd gradeX"><td></td></tr>
                                </tbody>
                            </table>
                        </div>

                        <div class="text-center">
                            <div class="fb-comments" expr:data-href='data:post.url' data-width="100%" data-numposts="5"></div>
                        </div>



                    </div>




                        <!------------------------>

                        <script src="/Assets/Client/js/cbpViewModeSwitch.js" type="text/javascript"></script>
                        <script src="/Assets/Client/js/classie.js" type="text/javascript"></script>
                    </div>
                <div class="products">                   
                    
                    <div class="tags">
                        <h4>Cùng tác giả</h4>
                        <ul class="tags_links"></ul>
                        <div class="bs-example">
                            <table class="table">
                                <tbody>
                                    @foreach (var item in cungtacgia)
                                    {
                                        <tr>
                                            <td class="type-info">
                                                <p><a href="@Url.Action("Chitiettruyen", "Doctruyen", new { id = @item.Matruyen })"><span id="p" style="font-family:Calibri; color:sienna;font-size:16px;"><strong>&nbsp;@item.Tentruyen</strong></span></a></p>
                                                <p>
                                                    @*✎&nbsp;&nbsp;@item.Tacgia<br />*@
                                                    ღ&nbsp;&nbsp;@item.Sochuong &nbsp;chương<br />
                                                </p>
                                            </td>


                                        </tr>

                                    }
                                    <tr>
                                        <td class="type-info">
                                            <a href="@Url.Action("Timkiemtruyentacgia","Timkiem",new { tg = @truyen.Tacgia })"><span style="color:dimgray"><strong>Xem thêm</strong></span></a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>

                    


                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- content-section-ends -->
        <!--========================================-->


       
     
      
    </div>


}
@section Facebook
{


    
     }
<style>

</style>

Webtruyen/Webtruyen/Views/Doctruyen/ChuongtruyenPartial.cshtml
@model List<Models.Framework.CHUONG>

<div class="bs-docs-example">
    <table class="table table-striped">
        <thead>
            <tr>
    @*<th class="text-center">Mã</th>*@
                        <th class="text-center"><span style="font-family: Arial; font-size: 19px;color:dimgray ">Chương</span></thclass="text-center">
                        <th class="text-center"><span style="font-family: Arial; font-size: 19px;color:dimgray ">Tên chương</span></th>
                        <th class="text-center"><span style="font-family: Arial; font-size: 19px;color:dimgray ">Cập nhật chương</span></th>
                    </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="row_@item.Machuong" class="odd gradeX">
                    @*<td class="text-center">@item.Machuong</td>*@
                    <td class="text-center"><span style="font-family:Arial; font-size: 20px;color:darkgray ">@item.Thutuchuong</span></td>
                    <td>
                        <span style="font-family:Arial; font-size: 20px;color:darkgray ">
                            <a href="@Url.Action("Docchuong","Doctruyen",new { id = @item.Machuong })">@item.Tenchuong</a>
                        </span>

                    </td>
                    <td class="text-center"><span style="font-size: 18px;color:darkgray ">@item.Capnhatchuong</span></td>
                </tr>
               
            }
        </tbody>
    </table>
</div>







    @*<ol>
        @foreach (var item in Model)
        {

            <li class="list-group-item1">

                <a href="@Url.Action("Docchuong","Doctruyen",new { id = @item.Machuong })">
                    <h2 class="bars">
                        <span style="font-family: Arial; font-size: 22px;color:gray ">
                            @item.Tenchuong
                        </span>
                    </h2>
                </a>

            </li>

        }

    </ol>*@

Webtruyen/Webtruyen/Views/Doctruyen/CungtacgiaPartial.cshtml
@model IEnumerable<Models.Framework.TRUYEN>



 
    @foreach (var item in Model)
    {
        <tr>
            <td class="type-info">
                <p><a href="@Url.Action("Chitiettruyen", "Doctruyen", new { id = @item.Matruyen })"><span id="p" style="font-family:Calibri; color:sienna;font-size:15px;"><strong>&nbsp;@item.Tentruyen</strong></span></a></p>
                <p>
                    ✎&nbsp;&nbsp;@item.Tacgia<br />
                </p>
            </td>

        </tr>

    }
@helper Truncate(string input, int length)
{
if (input == null)
{
}
else
{
    if (input.Length < length)
    {
            @input
    }
    else
    {
            @input.Substring(0, length)<text>...</text>
    }
}
}

  

Webtruyen/Webtruyen/Views/Doctruyen/DocChuong.cshtml
@model Models.Framework.CHUONG

@{
    ViewBag.Title = "DocChuong";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
    var truyen = (Models.Framework.TRUYEN)ViewBag.truyen;
    var chuong = (Models.Framework.CHUONG)ViewBag.chuongT;
    int chuongtruoc = (int)ViewBag.chuongtruoc;
    int chuongtiep = (int)ViewBag.chuongtiep;
    int sc = (int)truyen.Sochuong;
    var listC = (List<Models.Framework.CHUONG>)ViewBag.listC;
    
}
<link href="/Content/Docchuong.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        @Html.AntiForgeryToken()
        <br />
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Homeclient")">Trang chủ</a></li>
            <li><a href="@Url.Action("Timkiemtruyenabc","Timkiem")">Truyện chữ</a></li>
            <li><a href="@Url.Action("Chitiettruyen","Doctruyen",new { id = truyen.Matruyen })">@ViewBag.Tentruyen</a></li>
            <li class="active">@Html.DisplayFor(model => model.Tenchuong, new { htmlAttributes = new { @class = "form-control" } })</li>

        </ol>

        <!--<div id="page-wrapper">-->
        <div class="row">
            <div class="col-lg-12">
                <div class="container">
                   

                    <h1>                       <br />                                                    </h1>
                    <div class="bars"><p id="tieude" class="text-center">♥ⓛⓞⓥⓔ♥☜ (¯` ĐỌC TRUYỆN ´¯) ☞♥ⓛⓞⓥⓔ♥</p></div>
                    @* <h6 class="text-center">♥ⓛⓞⓥⓔ♥☜  (✿◠‿◠) (>‿◠)✌  ☞♥ⓛⓞⓥⓔ♥</h6>*@
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="container text-center">
                    <!--Tên truyện-->              
                  
                    <p id="tentruyentieude">
                        <span style="font-family: Arial; font-size: 210%;color:dodgerblue; font:bold ">
                            
                                <a href="@Url.Action("Chitiettruyen","Doctruyen",new { id = truyen.Matruyen })">@ViewBag.Tentruyen</a>
                        </span>
                    </p>

                </div>
            </div>
        </div>


        @*@Html.Action("TentruyenPartial", "Doctruyen", new { id = truyen.Matruyen })*@
        <div class="row">
            <div class="col-lg-12">
                <div class="container text-center">
                    <!--Tên chương-->
                    
                    <p id="tenchuongtieude">
                        <span style="font-family: Arial; font-size: 120%;color:gray ">
                            @Html.DisplayFor(model => model.Tenchuong, new { htmlAttributes = new { @class = "form-control" } })

                        </span>
                        <div class="fb-like" expr:data-href='data:post.url' data-layout="button" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>

                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="container">
                    @*<h4>                       <br />                                                    </h4>*@
                    <div>
                        <h5 class="text-center">
                            <br />––––•(-• Oº°‘¨ (name) ¨‘°ºO •-)•––––
                            <br /><br /><br />

                        </h5>
                    </div>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="container text-center">
                    @*<h4>                       <br />                                                    </h4>*@
                    <h1>┌∩┐(◕_◕)┌∩┐ <br /></h1>
                    <div class="row">

                        <input type="button" id="chuongdau" value="<Chương trước" class="btn btn-outline btn-info" disabled="disabled" />

                        <input type="button" id="chuongtruoc" value="<Chương trước" class="btn btn-outline btn-info" onclick="window.open('/Doctruyen/Docchuong/@chuongtruoc', '_self')" />
                        @*<input type="button" id="danhsach" value="↕" class="btn btn-outline btn-info" onclick=""/>*@
                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown" aria-controls="myTabDrop1-contents" aria-expanded="false"><span class="badge badge-primary" style="font-family:Calibri;font-size:18px;color:ghostwhite ">Chương</span></a>
                       
                        <ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop1" id="myTabDrop1-contents">
                            <li><span class="" style="font-family:Calibri;font-size:18px">&nbsp;&nbsp;Danh sách chương</span></li>  
                          
                                @foreach (var c in listC)
                                {
                                    <li><a href="/Doctruyen/Docchuong/@c.Machuong" aria-controls="dropdown2">@c.Thutuchuong. @c.Tenchuong</a></li>
                                }
                           
                            
                        </ul>
                        <input type="button" id="chuongtiep" value="Chương sau>" class="btn btn-outline btn-info" onclick="window.open('/Doctruyen/Docchuong/@chuongtiep', '_self')" />
                        <input type="button" id="chuongcuoi" value="Chương sau>" class="btn btn-outline btn-info" disabled="disabled" />
                    </div>
                   
                           
                                
                          
                      
                    




                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
            <div class="container">
                @*<h4>                       <br />                                                    </h4>*@
                <div>
                    <h5 class="text-center">
                        <br /><br /><br />

                        ▂ ▄ ▅ ▇ █ ♪♫♥ S T O D Y ♥♪♫ █ ▇ ▆ ▄ ▂<br /><br /><br />

                    </h5>
                </div>

            </div>
        </div>
    </div>
        <!--==========================================================-->
        <div class="row">
            <div class="col-lg-12">
                <div class="container ">
                    
                        @*<p><span style="font-family: Arial; font-size: 24px ">*@
                               <!--Nội dung-->
                    
                    <div class="noidung">
                        <span style="font-family:Arial; color:black">
                            @Html.Raw(@chuong.Noidong)
                        </span>
                    </div>
                    <p>
                        

                    </p>
                              @* @Html.DisplayFor(model => model.Noidong, new { htmlAttributes = new { @class = "form-control" } })*@
                         @*</span>
    
                        </p>*@
                        <!--Nội dung-->
                       
                    
                </div>
            </div>
        </div>
        <!--==========================================================-->
        <div class="row">
            <div class="col-lg-12">
                <div class="container">
                    @*<h4>                       <br />                                                    </h4>*@
                    <div>
                        <h5 class="text-center">
                            <br /><br /><br />
                            ▂ ▄ ▅ ▇ █ ♪♫♥ S T O D Y ♥♪♫ █ ▇ ▆ ▄ ▂<br /><br /><br /><br />

                        </h5>
                    </div>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="container text-center">
                    @*<h4>                       <br />                                                    </h4>*@
                    <h1>┌∩┐(◠‿◠)┌∩┐ <br /></h1>
                    <div class="row">
                       
                            <input type="button" id="chuongdau" value="<Chương trước" class="btn btn-outline btn-info" disabled="disabled" />
                        
                            <input type="button" id="chuongtruoc" value="<Chương trước" class="btn btn-outline btn-info" onclick="window.open('/Doctruyen/Docchuong/@chuongtruoc', '_self')" />
                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown" aria-controls="myTabDrop1-contents" aria-expanded="false"><span class="badge badge-primary" style="font-family:Calibri;font-size:18px;color:ghostwhite ">Chương</span></a>

                        <ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop1" id="myTabDrop1-contents">
                            <li><span class="" style="font-family:Calibri;font-size:18px">&nbsp;&nbsp;Danh sách chương</span></li>

                            @foreach (var c in listC)
                            {
                                <li><a href="/Doctruyen/Docchuong/@c.Machuong" aria-controls="dropdown2">@c.Thutuchuong. @c.Tenchuong</a></li>
                            }


                        </ul>



                            <input type="button" id="chuongtiep" value="Chương sau>" class="btn btn-outline btn-info" onclick="window.open('/Doctruyen/Docchuong/@chuongtiep', '_self')" />
                            <input type="button" id="chuongcuoi" value="Chương sau>" class="btn btn-outline btn-info" disabled="disabled" />
                    </div>
                   
                    <p><br /><br /></p>


                </div>
            </div>
        </div>




    </div>
    <script>
        if (@chuongtiep == 0)
        {
            $(chuongtiep).hide();
            $(chuongcuoi).show();
        }
        else
        {
            $(chuongcuoi).hide();
            $(chuongtiep).show();
        }
    </script>
    <script>
        if (@chuongtruoc == 0)
        {
            $(chuongtruoc).hide();
            $(chuongdau).show();
        }
        else
        {
            $(chuongdau).hide();
            $(chuongtruoc).show();
        }
        

    </script>









}
@section Facebook
{
<h3 class="first"><p><span style="font-family: Arial; font-size: 28px;color:dimgray "><br />Bình luận</span></p></h3>
<div class="">
    <table class="table">
        <tbody>
            <tr class="text-center odd gradeX"><td></td></tr>
        </tbody>
    </table>
</div>

<div class="text-center">
    @*<div class="fb-comments" expr:data-href='data:post.url' data-width="100%" data-numposts="5"></div>*@
    @*<div class="fb-comments" data-href="" data-width="100%" data-numposts="5"></div>*@
    <div class="fb-comments" data-href="http://www.truyenchuonline.somee.com/Doctruyen/Chitiettruyen/@truyen.Matruyen" data-width="100%" data-numposts="5"></div>
</div>
    

}

Webtruyen/Webtruyen/Views/Doctruyen/TentruyenPartial.cshtml
@model Models.Framework.TRUYEN